AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${AWS::StackName}-group"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user1"
  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user2"
  IAMUser3:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user3"
  IAMUser4:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user4"