AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${AWS::StackName}-group"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user1"
      Groups:
        - !Ref IAMGroup
  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user2"
      Groups:
        - !Ref IAMGroup
  IAMUser3:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user3"
      Groups:
        - !Ref IAMGroup
  IAMUser4:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user4"
      Groups:
        - !Ref IAMGroup